version: '3.7'

services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "123456@aA"
    ports:
      - 1433:1433
    volumes:
      - ./sql-server-autogenvolume:/var/opt/mssql
      
volumes:
  sql-server-autogenvolume: